name: audio_service_smtc
description: Windows implementation for audio service using System Media Transport Controls
version: 0.1.0
homepage: https://github.com/yourusername/audio_service_smtc

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service_platform_interface: ^0.1.3
  ffi: ^2.1.0
  plugin_platform_interface: ^2.1.8
  win32: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ">=6.0.0 <8.0.0"
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SmtcPluginCApi
